services:
  msg:
    image: akvicor/msg:v0.1.7
    restart: always
    volumes:
      - /path/to/msg/data/msg-data:/data
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/sys/info/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.2
    restart: always
    volumes:
      - /path/to/msg/data/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=msg
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d msg"]
      interval: 10s
      timeout: 5s
      retries: 5


